### ISSUE TITLE
文字列よりもシンボルの方が高速なためシンボル表記に書き換える

### ISSUE THREAD

**Issue by norotime** [naokiohshima/daikadai6#3]
https://github.com/naokiohshima/daikadai6/blob/1a81a8ccf588b636373757a8a1bb22e6e7ad3885/app/controllers/comments_controller.rb#L35

シンボルを使うメリットは

新しく文字列を生成しない分やや効率がよく、比較も高速。
文字の意味がはっきりするのでコードが読みやすくなる
immutable なので内容を書き換えられる心配がない

です。
https://docs.ruby-lang.org/ja/latest/class/Symbol.html

**Comment by naokiohshima** [comment]
c43f9d0abcd23a97c6e5b4b19cdd0e77b6aab9f8
