### ISSUE TITLE
100万件など大量データを想定し、DBがハングしないようにallメソッド全件取得を見直す

### ISSUE THREAD

**Issue by norotime** [naokiohshima/daikadai6#6]
https://github.com/naokiohshima/daikadai6/blob/1a81a8ccf588b636373757a8a1bb22e6e7ad3885/app/controllers/conversations_controller.rb#L5

@naokiohshima モデルにlimitをつけるなど検討してください。
https://railsguides.jp/active_record_querying.html#limit%E3%81%A8offset

**Comment by naokiohshima** [comment]
6ff0fefee1114b4cf5595255db7cc10f949c1ba9

**Comment by norotime** [comment]
@naokiohshima コミットメッセージにイシュー番号を記載すると紐づきますよ！
