### ISSUE TITLE
認証フィルタは全コントローラに適用させるならapplicationコントローラに一行だけ記述する

### ISSUE THREAD

**Issue by norotime** [naokiohshima/daikadai6#7]
https://github.com/naokiohshima/daikadai6/blob/1a81a8ccf588b636373757a8a1bb22e6e7ad3885/app/controllers/events_controller.rb#L2

**Comment by naokiohshima** [comment]
c43f9d0abcd23a97c6e5b4b19cdd0e77b6aab9f8

**Comment by naokiohshima** [comment]
5c4e9f4b172449dca7d4b0f385a3abc20d2a79c5
