### ISSUE TITLE
不要なコメント行は全て削除する

### ISSUE THREAD

**Issue by norotime** [naokiohshima/daikadai6#8]
https://github.com/naokiohshima/daikadai6/blob/1a81a8ccf588b636373757a8a1bb22e6e7ad3885/app/models/ability.rb#L9

**Comment by norotime** [comment]
@naokiohshima ここも。設定までは消さないでね。
https://github.com/naokiohshima/daikadai6/blob/1a81a8ccf588b636373757a8a1bb22e6e7ad3885/app/assets/stylesheets/application.css#L2

**Comment by naokiohshima** [comment]
直しました　確認お願いします。

**Comment by norotime** [comment]
@naokiohshima 直したら、その関連するコミットをこのイシューに紐づけて欲しいです。

**Comment by norotime** [comment]
@naokiohshima イシューを対応したらクローズしてくださいね〜＝！

**Comment by naokiohshima** [comment]
6ff0fefee1114b4cf5595255db7cc10f949c1ba9

**Comment by naokiohshima** [comment]
c43f9d0abcd23a97c6e5b4b19cdd0e77b6aab9f8

**Comment by naokiohshima** [comment]
c43f9d0abcd23a97c6e5b4b19cdd0e77b6aab9f8
